import type { TxTraceResponse } from "./types";

const HASH = `0x${"6c13".repeat(16)}`;
const USER = "0x5e196f3b54978b2a99f58fe8ff4db73bf4dd4a8b";
const MEV = "0x6c13e8a16cdbd2e2dd19f70d87c1372c3563ec05";
const UNI = "0xc76225124f3caab07f609b1d147a31de43926cd6";
const SUSHI = "0x23a9292830fc80db7f563edb28d2fe6fb47f8624";
const BUILDER = "0x483bb106fce9647bdf1e7877bf73ce8b0bad5f97";
const WETH = "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2";

export const sampleTrace: TxTraceResponse = {
  tx: {
    hash: HASH,
    chainId: "1",
    from: USER,
    to: MEV,
    valueRaw: "0",
    status: "success",
    blockNumber: "0x14f8a31",
  },
  transfers: [
    {
      id: "topLevelCall:0",
      kind: "topLevelCall",
      txHash: HASH,
      from: USER,
      to: MEV,
      assetKey: "native:ETH",
      tokenAddress: null,
      tokenName: null,
      symbol: "ETH",
      decimals: 18,
      valueRaw: "0",
      valueFormatted: "0.00",
      label: "0.00 ETH call",
      index: 0,
      displayIndex: 1,
      failed: false,
      metadataWarnings: [],
    },
    {
      id: "erc20:2",
      kind: "erc20",
      txHash: HASH,
      from: MEV,
      to: SUSHI,
      assetKey: "erc20:sfi",
      tokenAddress: "0x8888888888888888888888888888888888888888",
      tokenName: "Sample Finance",
      symbol: "SFI",
      decimals: 18,
      valueRaw: "2210000000000000000",
      valueFormatted: "2.21",
      label: "2.21 SFI",
      index: 2,
      displayIndex: 2,
      failed: false,
      metadataWarnings: [],
    },
    {
      id: "erc20:3",
      kind: "erc20",
      txHash: HASH,
      from: MEV,
      to: UNI,
      assetKey: "erc20:sfi",
      tokenAddress: "0x8888888888888888888888888888888888888888",
      tokenName: "Sample Finance",
      symbol: "SFI",
      decimals: 18,
      valueRaw: "2210000000000000000",
      valueFormatted: "2.21",
      label: "2.21 SFI",
      index: 3,
      displayIndex: 3,
      failed: false,
      metadataWarnings: [],
    },
    {
      id: "erc20:4",
      kind: "erc20",
      txHash: HASH,
      from: MEV,
      to: SUSHI,
      assetKey: "erc20:weth",
      tokenAddress: WETH,
      tokenName: "Wrapped Ether",
      symbol: "WETH",
      decimals: 18,
      valueRaw: "135300000000000000",
      valueFormatted: "0.1353",
      label: "0.1353 WETH",
      index: 4,
      displayIndex: 4,
      failed: false,
      metadataWarnings: [],
    },
    {
      id: "native:8",
      kind: "internal",
      txHash: HASH,
      from: MEV,
      to: BUILDER,
      assetKey: "native:ETH",
      tokenAddress: null,
      tokenName: null,
      symbol: "ETH",
      decimals: 18,
      valueRaw: "2400000000000000",
      valueFormatted: "0.0024",
      label: "0.0024 ETH",
      index: 8,
      displayIndex: null,
      failed: false,
      metadataWarnings: [],
    },
    {
      id: "native:6",
      kind: "internal",
      txHash: HASH,
      from: MEV,
      to: WETH,
      assetKey: "native:ETH",
      tokenAddress: null,
      tokenName: null,
      symbol: "ETH",
      decimals: 18,
      valueRaw: "3300000000000000",
      valueFormatted: "0.0033",
      label: "0.0033 ETH",
      index: 6,
      displayIndex: 6,
      failed: false,
      metadataWarnings: [],
    },
    {
      id: "erc20:7",
      kind: "erc20",
      txHash: HASH,
      from: MEV,
      to: WETH,
      assetKey: "erc20:weth",
      tokenAddress: WETH,
      tokenName: "Wrapped Ether",
      symbol: "WETH",
      decimals: 18,
      valueRaw: "3300000000000000",
      valueFormatted: "0.0033",
      label: "0.0033 WETH",
      index: 7,
      displayIndex: 7,
      failed: false,
      metadataWarnings: [],
    },
  ],
  nodes: [
    {
      id: USER.toLowerCase(),
      address: USER,
      shortAddress: "0x5e196f...dd4a8b",
      label: "Sender",
      roles: ["sender"],
      transferCount: 1,
      outgoingCount: 1,
      incomingCount: 0,
    },
    {
      id: MEV.toLowerCase(),
      address: MEV,
      shortAddress: "0x6c13e8...63ec05",
      label: "Receiver",
      roles: ["receiver"],
      transferCount: 6,
      outgoingCount: 5,
      incomingCount: 1,
    },
    {
      id: UNI.toLowerCase(),
      address: UNI,
      shortAddress: "0xc76225...926cd6",
      label: "Uniswap V2",
      roles: ["internal"],
      transferCount: 1,
      outgoingCount: 0,
      incomingCount: 1,
    },
    {
      id: SUSHI.toLowerCase(),
      address: SUSHI,
      shortAddress: "0x23a929...7f8624",
      label: "SushiSwap",
      roles: ["internal"],
      transferCount: 2,
      outgoingCount: 0,
      incomingCount: 2,
    },
    {
      id: BUILDER.toLowerCase(),
      address: BUILDER,
      shortAddress: "0x483bb1...ad5f97",
      label: "Titan Builder",
      roles: ["internal"],
      transferCount: 1,
      outgoingCount: 0,
      incomingCount: 1,
    },
    {
      id: WETH.toLowerCase(),
      address: WETH,
      shortAddress: "0xc02aaa...756cc2",
      label: "WETH",
      roles: ["internal"],
      transferCount: 2,
      outgoingCount: 0,
      incomingCount: 2,
    },
  ],
  edges: [
    {
      id: `edge:${USER.toLowerCase()}->${MEV.toLowerCase()}:top-level-call`,
      source: USER.toLowerCase(),
      target: MEV.toLowerCase(),
      label: "[1] 0.00 ETH call",
      displayIndexes: [1],
      transferIds: ["topLevelCall:0"],
      kinds: ["topLevelCall"],
      transferCount: 1,
      assets: [
        {
          assetKey: "native:ETH",
          symbol: "ETH",
          decimals: 18,
          tokenAddress: null,
          valueRaw: "0",
          valueFormatted: "0.00",
          transferCount: 1,
        },
      ],
      hasFailed: false,
    },
    {
      id: `edge:${MEV.toLowerCase()}->${SUSHI.toLowerCase()}:erc20:sfi`,
      source: MEV.toLowerCase(),
      target: SUSHI.toLowerCase(),
      label: "[2] 2.21 SFI",
      displayIndexes: [2],
      transferIds: ["erc20:2"],
      kinds: ["erc20"],
      transferCount: 1,
      assets: [
        {
          assetKey: "erc20:sfi",
          symbol: "SFI",
          decimals: 18,
          tokenAddress: "0x8888888888888888888888888888888888888888",
          valueRaw: "2210000000000000000",
          valueFormatted: "2.21",
          transferCount: 1,
        },
      ],
      hasFailed: false,
    },
    {
      id: `edge:${MEV.toLowerCase()}->${SUSHI.toLowerCase()}:erc20:weth`,
      source: MEV.toLowerCase(),
      target: SUSHI.toLowerCase(),
      label: "[4] 0.1353 WETH",
      displayIndexes: [4],
      transferIds: ["erc20:4"],
      kinds: ["erc20"],
      transferCount: 1,
      assets: [
        {
          assetKey: "erc20:weth",
          symbol: "WETH",
          decimals: 18,
          tokenAddress: WETH,
          valueRaw: "135300000000000000",
          valueFormatted: "0.1353",
          transferCount: 1,
        },
      ],
      hasFailed: false,
    },
    {
      id: `edge:${MEV.toLowerCase()}->${UNI.toLowerCase()}:erc20:sfi`,
      source: MEV.toLowerCase(),
      target: UNI.toLowerCase(),
      label: "[3] 2.21 SFI",
      displayIndexes: [3],
      transferIds: ["erc20:3"],
      kinds: ["erc20"],
      transferCount: 1,
      assets: [
        {
          assetKey: "erc20:sfi",
          symbol: "SFI",
          decimals: 18,
          tokenAddress: "0x8888888888888888888888888888888888888888",
          valueRaw: "2210000000000000000",
          valueFormatted: "2.21",
          transferCount: 1,
        },
      ],
      hasFailed: false,
    },
    {
      id: `edge:${MEV.toLowerCase()}->${BUILDER.toLowerCase()}:native:ETH`,
      source: MEV.toLowerCase(),
      target: BUILDER.toLowerCase(),
      label: "[?] 0.0024 ETH",
      displayIndexes: [null],
      transferIds: ["native:8"],
      kinds: ["internal"],
      transferCount: 1,
      assets: [
        {
          assetKey: "native:ETH",
          symbol: "ETH",
          decimals: 18,
          tokenAddress: null,
          valueRaw: "2400000000000000",
          valueFormatted: "0.0024",
          transferCount: 1,
        },
      ],
      hasFailed: false,
    },
    {
      id: `edge:${MEV.toLowerCase()}->${WETH.toLowerCase()}:native:ETH`,
      source: MEV.toLowerCase(),
      target: WETH.toLowerCase(),
      label: "[6] 0.0033 ETH",
      displayIndexes: [6],
      transferIds: ["native:6"],
      kinds: ["internal"],
      transferCount: 1,
      assets: [
        {
          assetKey: "native:ETH",
          symbol: "ETH",
          decimals: 18,
          tokenAddress: null,
          valueRaw: "3300000000000000",
          valueFormatted: "0.0033",
          transferCount: 1,
        },
      ],
      hasFailed: false,
    },
    {
      id: `edge:${MEV.toLowerCase()}->${WETH.toLowerCase()}:erc20:weth`,
      source: MEV.toLowerCase(),
      target: WETH.toLowerCase(),
      label: "[7] 0.0033 WETH",
      displayIndexes: [7],
      transferIds: ["erc20:7"],
      kinds: ["erc20"],
      transferCount: 1,
      assets: [
        {
          assetKey: "erc20:weth",
          symbol: "WETH",
          decimals: 18,
          tokenAddress: WETH,
          valueRaw: "3300000000000000",
          valueFormatted: "0.0033",
          transferCount: 1,
        },
      ],
      hasFailed: false,
    },
  ],
  warnings: [],
};
